### ISSUE TITLE
Show number of data points in each bin

### ISSUE THREAD

**Issue by HLasse** [Dansk-Data-Science-Community/danish-data-science-salary-survey#26]
Great work!! 
It would be a nice feature to see how many datapoints/individuals each boxplot is based on when hovering or presented at the top of each bar. [Seems to possible](https://stackoverflow.com/questions/69881191/adding-counts-to-plotly-boxplots).

**Comment by JungeAlexander** [comment]
I agree - great work and I would also like to see the N for each box. I think the main dashboard is built on matplotlib/seaborn and [here](https://stackoverflow.com/questions/63490070/plotting-number-of-observations-on-seaborn-boxplot-for-subplots-python) is a simple example how counts can be added.

**Comment by saattrupdan** [comment]
@HLasse @JungeAlexander This feature is live now 🎉
